[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.2", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.42"
serde_json = "1.0.145"
thiserror = "2.0.17"
