[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
axum = "0.8.6"
tokio = {version = "1.47.1", features = ["full"]}
dotenvy = "0.15.7"
thiserror = "2.0.17"