"""add oauth tables

Revision ID: 036a5a3ea657
Revises: 493e7a1bfb65
Create Date: 2025-12-30 11:23:51.626346

"""
from datetime import datetime, timedelta, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from passlib.context import CryptContext


# revision identifiers, used by Alembic.
revision: str = '036a5a3ea657'
down_revision: Union[str, Sequence[str], None] = '493e7a1bfb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Password hashing context
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client_secret_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_user_id'), 'oauth_clients', ['user_id'], unique=False)
    op.create_table('oauth_access_tokens',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_access_tokens_access_token'), 'oauth_access_tokens', ['access_token'], unique=True)
    op.create_index(op.f('ix_oauth_access_tokens_client_id'), 'oauth_access_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_access_tokens_expires_at'), 'oauth_access_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_access_tokens_is_revoked'), 'oauth_access_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_oauth_access_tokens_refresh_token'), 'oauth_access_tokens', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_oauth_access_tokens_refresh_token_expires_at'), 'oauth_access_tokens', ['refresh_token_expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_access_tokens_user_id'), 'oauth_access_tokens', ['user_id'], unique=False)
    op.create_table('oauth_authorization_codes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_authorization_codes_client_id'), 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_code'), 'oauth_authorization_codes', ['code'], unique=True)
    op.create_index(op.f('ix_oauth_authorization_codes_expires_at'), 'oauth_authorization_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_user_id'), 'oauth_authorization_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###






def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_authorization_codes_user_id'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_expires_at'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_code'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_client_id'), table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_access_tokens_user_id'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_refresh_token_expires_at'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_refresh_token'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_is_revoked'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_expires_at'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_client_id'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_access_token'), table_name='oauth_access_tokens')
    op.drop_table('oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_clients_user_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
