"""add chat_conversation_attachments table

Revision ID: 0dff7c4153d407b4
Revises: f5a347747e4b
Create Date: 2026-05-12 15:52:00.000000

"""

import json
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dff7c4153d407b4"
down_revision: Union[str, Sequence[str], None] = "f5a347747e4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create chat_conversation_attachments table and back-fill from active_drive_file_ids."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversation_attachments",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("drive_file_id", sa.Integer(), nullable=False),
        sa.Column("attached_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["chat_conversations.id"],
            name=op.f("chat_conversation_attachments_conversation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["drive_file_id"],
            ["drive_files.id"],
            name=op.f("chat_conversation_attachments_drive_file_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_conversation_attachments_pkey")),
        sa.UniqueConstraint(
            "conversation_id",
            "drive_file_id",
            name="uq_conv_attachment",
        ),
    )
    op.create_index(
        "idx_conv_attach_conversation",
        "chat_conversation_attachments",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_conv_attach_drive_file",
        "chat_conversation_attachments",
        ["drive_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Back-fill from active_drive_file_ids JSON
    bind = op.get_bind()
    rows = bind.execute(
        sa.text("SELECT id, active_drive_file_ids FROM chat_conversations WHERE active_drive_file_ids IS NOT NULL")
    ).fetchall()

    for conv_id, raw_ids in rows:
        try:
            ids = json.loads(raw_ids)
            for fid in ids:
                try:
                    bind.execute(
                        sa.text(
                            "INSERT OR IGNORE INTO chat_conversation_attachments "
                            "(conversation_id, drive_file_id, attached_at, created_at, updated_at) "
                            "VALUES (:cid, :fid, datetime('now'), datetime('now'), datetime('now'))"
                        ),
                        {"cid": conv_id, "fid": fid},
                    )
                except Exception:
                    # Skip individual file IDs that fail to insert
                    pass
        except (ValueError, TypeError):
            # Skip conversations with malformed JSON
            pass


def downgrade() -> None:
    """Drop chat_conversation_attachments table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_conv_attach_drive_file", table_name="chat_conversation_attachments")
    op.drop_index("idx_conv_attach_conversation", table_name="chat_conversation_attachments")
    op.drop_table("chat_conversation_attachments")
    # ### end Alembic commands ###
