"""User Plugin Table

Revision ID: 1761ebd363b9
Revises: c697de92eb38
Create Date: 2025-12-08 13:40:04.015336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1761ebd363b9'
down_revision: Union[str, Sequence[str], None] = 'c697de92eb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_plugins',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plugins_is_deleted'), 'user_plugins', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_plugins_plugin_name'), 'user_plugins', ['plugin_name'], unique=False)
    op.create_index(op.f('ix_user_plugins_user_id'), 'user_plugins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_plugins_user_id'), table_name='user_plugins')
    op.drop_index(op.f('ix_user_plugins_plugin_name'), table_name='user_plugins')
    op.drop_index(op.f('ix_user_plugins_is_deleted'), table_name='user_plugins')
    op.drop_table('user_plugins')
    # ### end Alembic commands ###
