"""add whitelisted_email table

Revision ID: 2899d4e35c26
Revises: i2b3c4d5e6f7
Create Date: 2026-04-27

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2899d4e35c26"
down_revision: Union[str, Sequence[str], None] = "i2b3c4d5e6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_table(
        "whitelisted_email",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("entry_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("added_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["added_by_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_index(op.f("ix_whitelisted_email_value"), "whitelisted_email", ["value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_whitelisted_email_value"), table_name="whitelisted_email")
    op.drop_table("whitelisted_email")
    # ### end Alembic commands ###
