"""replace_api_key_id_with_llm_config_id_on_conversations

Revision ID: 2e34759ac1e1
Revises: e8530a5a5a0e
Create Date: 2026-04-21 13:03:27.709257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e34759ac1e1'
down_revision: Union[str, Sequence[str], None] = 'e8530a5a5a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('llm_config_id', sa.Integer(), nullable=True))
    # ed5bc53f5b16 copied chat_provider_api_keys into llm_configs preserving IDs.
    # Any API keys created after that migration are missing from llm_configs; sync them now
    # using the same projection so the subsequent FK constraint can be satisfied.
    op.execute("""
        INSERT INTO llm_configs
            (is_deleted, deleted_at, created_at, updated_at,
             id, user_id, name, provider, model,
             encrypted_key, masked_key, is_active, last_used_at)
        SELECT
            COALESCE(is_deleted, false),
            deleted_at, created_at, updated_at, id, user_id,
            provider || '-' || id::text AS name,
            provider, '' AS model,
            encrypted_key, masked_key, is_active, last_used_at
        FROM chat_provider_api_keys
        WHERE id NOT IN (SELECT id FROM llm_configs)
    """)
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('llm_configs', 'id'),
            COALESCE((SELECT MAX(id) FROM llm_configs), 0)
        )
    """)
    op.execute(
        "UPDATE chat_conversations SET llm_config_id = api_key_id WHERE api_key_id IS NOT NULL"
    )
    op.drop_index(op.f('ix_chat_conversations_api_key_id'), table_name='chat_conversations')
    op.create_index(op.f('ix_chat_conversations_llm_config_id'), 'chat_conversations', ['llm_config_id'], unique=False)
    op.drop_constraint(op.f('chat_conversations_api_key_id_fkey'), 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'chat_conversations', 'llm_configs', ['llm_config_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chat_conversations', 'api_key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute(
        "UPDATE chat_conversations SET api_key_id = llm_config_id WHERE llm_config_id IS NOT NULL"
    )
    op.drop_constraint(None, 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('chat_conversations_api_key_id_fkey'), 'chat_conversations', 'chat_provider_api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_chat_conversations_llm_config_id'), table_name='chat_conversations')
    op.create_index(op.f('ix_chat_conversations_api_key_id'), 'chat_conversations', ['api_key_id'], unique=False)
    op.drop_column('chat_conversations', 'llm_config_id')
    # ### end Alembic commands ###
