"""replace_api_key_id_with_llm_config_id_on_conversations

Revision ID: 2e34759ac1e1
Revises: ed5bc53f5b16
Create Date: 2026-04-21 13:03:27.709257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e34759ac1e1'
down_revision: Union[str, Sequence[str], None] = 'ed5bc53f5b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('llm_config_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_chat_conversations_api_key_id'), table_name='chat_conversations')
    op.create_index(op.f('ix_chat_conversations_llm_config_id'), 'chat_conversations', ['llm_config_id'], unique=False)
    op.drop_constraint(op.f('chat_conversations_api_key_id_fkey'), 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'chat_conversations', 'llm_configs', ['llm_config_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chat_conversations', 'api_key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('chat_conversations_api_key_id_fkey'), 'chat_conversations', 'chat_provider_api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_chat_conversations_llm_config_id'), table_name='chat_conversations')
    op.create_index(op.f('ix_chat_conversations_api_key_id'), 'chat_conversations', ['api_key_id'], unique=False)
    op.drop_column('chat_conversations', 'llm_config_id')
    # ### end Alembic commands ###
