"""add slack plugin tables

Revision ID: 5ae910dbda5d
Revises: a33f0a38c389
Create Date: 2026-04-14 18:36:17.804015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae910dbda5d'
down_revision: Union[str, Sequence[str], None] = 'a33f0a38c389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspaces',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('bot_token_encrypted', sa.Text(), nullable=False),
    sa.Column('bot_user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_workspaces_is_active'), 'slack_workspaces', ['is_active'], unique=False)
    op.create_index(op.f('ix_slack_workspaces_is_deleted'), 'slack_workspaces', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_slack_workspaces_team_id'), 'slack_workspaces', ['team_id'], unique=False)
    op.create_index(op.f('ix_slack_workspaces_user_id'), 'slack_workspaces', ['user_id'], unique=False)
    op.create_table('slack_bot_response_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('slack_channel', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slack_user', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slack_ts', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('rag_matched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_bot_response_logs_workspace_id'), 'slack_bot_response_logs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_bot_response_logs_workspace_id'), table_name='slack_bot_response_logs')
    op.drop_table('slack_bot_response_logs')
    op.drop_index(op.f('ix_slack_workspaces_user_id'), table_name='slack_workspaces')
    op.drop_index(op.f('ix_slack_workspaces_team_id'), table_name='slack_workspaces')
    op.drop_index(op.f('ix_slack_workspaces_is_deleted'), table_name='slack_workspaces')
    op.drop_index(op.f('ix_slack_workspaces_is_active'), table_name='slack_workspaces')
    op.drop_table('slack_workspaces')
    # ### end Alembic commands ###
