"""drop chat_provider_api_key

Revision ID: 5c3e0d64672c
Revises: 2e34759ac1e1
Create Date: 2026-04-21 17:06:00.824894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c3e0d64672c'
down_revision: Union[str, Sequence[str], None] = '2e34759ac1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_provider_active'), table_name='chat_provider_api_keys')
    op.drop_index(op.f('ix_chat_provider_api_keys_is_deleted'), table_name='chat_provider_api_keys')
    op.drop_index(op.f('ix_chat_provider_api_keys_provider'), table_name='chat_provider_api_keys')
    op.drop_index(op.f('ix_chat_provider_api_keys_user_id'), table_name='chat_provider_api_keys')
    op.drop_table('chat_provider_api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_provider_api_keys',
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('encrypted_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('masked_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_provider_api_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_provider_api_keys_pkey'))
    )
    op.create_index(op.f('ix_chat_provider_api_keys_user_id'), 'chat_provider_api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_provider_api_keys_provider'), 'chat_provider_api_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_chat_provider_api_keys_is_deleted'), 'chat_provider_api_keys', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_user_provider_active'), 'chat_provider_api_keys', ['user_id', 'provider', 'is_active'], unique=False)
    # Restore row data from llm_configs, which holds all keys as of 2e34759ac1e1.
    op.execute("""
        INSERT INTO chat_provider_api_keys
            (is_deleted, deleted_at, created_at, updated_at,
             id, user_id, provider, encrypted_key, masked_key, is_active, last_used_at)
        SELECT
            is_deleted, deleted_at, created_at, updated_at,
            id, user_id, provider, encrypted_key, masked_key, is_active, last_used_at
        FROM llm_configs
    """)
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('chat_provider_api_keys', 'id'),
            COALESCE((SELECT MAX(id) FROM chat_provider_api_keys), 0)
        )
    """)
    # ### end Alembic commands ###
