"""create conversation_active_drive_files table

Revision ID: 679e83f6c153
Revises: 9c055c4d542a
Create Date: 2026-04-25 06:41:58.227012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "679e83f6c153"
down_revision: Union[str, Sequence[str], None] = "9c055c4d542a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_active_drive_files",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("drive_file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["chat_conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["drive_file_id"], ["drive_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "drive_file_id"),
    )
    op.create_index(
        op.f("ix_conversation_active_drive_files_conversation_id"),
        "conversation_active_drive_files",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_active_drive_files_drive_file_id"),
        "conversation_active_drive_files",
        ["drive_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_active_drive_files_drive_file_id"), table_name="conversation_active_drive_files"
    )
    op.drop_index(
        op.f("ix_conversation_active_drive_files_conversation_id"), table_name="conversation_active_drive_files"
    )
    op.drop_table("conversation_active_drive_files")
    # ### end Alembic commands ###
