"""add permissions rbac tables

Revision ID: 7ee9891441d3
Revises: 19422defc371
Create Date: 2026-06-18 15:01:23.560289

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ee9891441d3"
down_revision: Union[str, Sequence[str], None] = "19422defc371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=True)
    op.create_table(
        "role_assignment",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("scope_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("scope_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_assignment_is_deleted"), "role_assignment", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_role_assignment_role_id"), "role_assignment", ["role_id"], unique=False)
    op.create_index(op.f("ix_role_assignment_scope_id"), "role_assignment", ["scope_id"], unique=False)
    op.create_index(op.f("ix_role_assignment_scope_type"), "role_assignment", ["scope_type"], unique=False)
    op.create_index(op.f("ix_role_assignment_user_id"), "role_assignment", ["user_id"], unique=False)
    op.create_table(
        "role_permission",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_role_assignment_user_id"), table_name="role_assignment")
    op.drop_index(op.f("ix_role_assignment_scope_type"), table_name="role_assignment")
    op.drop_index(op.f("ix_role_assignment_scope_id"), table_name="role_assignment")
    op.drop_index(op.f("ix_role_assignment_role_id"), table_name="role_assignment")
    op.drop_index(op.f("ix_role_assignment_is_deleted"), table_name="role_assignment")
    op.drop_table("role_assignment")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
