"""remove active_drive_file columns from chat_conversations

Revision ID: 87e049122b83
Revises: 0dff7c4153d407b4
Create Date: 2026-05-14 16:39:53.870229

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87e049122b83"
down_revision: Union[str, Sequence[str], None] = "0dff7c4153d407b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_conversations_active_drive_file_id"), table_name="chat_conversations")
    op.drop_constraint(op.f("chat_conversations_active_drive_file_id_fkey"), "chat_conversations", type_="foreignkey")
    op.drop_column("chat_conversations", "active_drive_file_ids")
    op.drop_column("chat_conversations", "active_drive_file_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_conversations", sa.Column("active_drive_file_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "chat_conversations", sa.Column("active_drive_file_ids", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("chat_conversations_active_drive_file_id_fkey"),
        "chat_conversations",
        "drive_files",
        ["active_drive_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_chat_conversations_active_drive_file_id"), "chat_conversations", ["active_drive_file_id"], unique=False
    )
    # ### end Alembic commands ###
