"""fix unexpected schema differences

Revision ID: acc6f4381f88
Revises: 21c447527dc6
Create Date: 2026-04-17 15:04:32.731375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acc6f4381f88'
down_revision: Union[str, Sequence[str], None] = '21c447527dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversation_uuid'), table_name='chat_conversations')
    op.create_index(op.f('ix_chat_conversations_uuid'), 'chat_conversations', ['uuid'], unique=True)
    op.alter_column('drive_files', 'modified_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('drive_files', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('drive_files', 'rag_error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('drive_folders', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('drive_folders', 'sync_error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('drive_oauth_tokens', 'token_expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('drive_oauth_tokens_user_id_key'), 'drive_oauth_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('drive_oauth_tokens_user_id_key'), 'drive_oauth_tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('drive_oauth_tokens', 'token_expiry',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('drive_folders', 'sync_error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drive_folders', 'last_synced_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('drive_files', 'rag_error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drive_files', 'last_synced_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('drive_files', 'modified_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_conversations_uuid'), table_name='chat_conversations')
    op.create_index(op.f('idx_conversation_uuid'), 'chat_conversations', ['uuid'], unique=True)
    # ### end Alembic commands ###
