"""make api_key_id nullable

Revision ID: b45bf4146679
Revises: 4c5228ae23ae
Create Date: 2026-02-04 19:39:17.554031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b45bf4146679'
down_revision: Union[str, Sequence[str], None] = '4c5228ae23ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_conversations', 'api_key_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_conversations', ['conversation_id'], ['id'])
    op.alter_column('chat_provider_api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_provider_api_keys', 'last_used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', 'chat_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_conversations', 'api_key_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
