"""slack_log_improvements

Revision ID: d300f558a4b4
Revises: f5a347747e4b
Create Date: 2026-05-14 18:56:02.577570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd300f558a4b4'
down_revision: Union[str, Sequence[str], None] = 'f5a347747e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_connection_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('connected', 'disconnected', name='connectioneventtype'), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_connection_logs_workspace_id'), 'slack_connection_logs', ['workspace_id'], unique=False)
    responsetype = sa.Enum('rag_match', 'fallback', 'greeting', 'config_incomplete', 'plugin_disabled', 'legacy', name='responsetype')
    responsetype.create(op.get_bind(), checkfirst=True)
    op.add_column('slack_bot_response_logs', sa.Column('response_type', sa.Enum('rag_match', 'fallback', 'greeting', 'config_incomplete', 'plugin_disabled', 'legacy', name='responsetype'), server_default='legacy', nullable=False))
    op.add_column('slack_bot_response_logs', sa.Column('slack_user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('slack_bot_response_logs', sa.Column('slack_channel_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_bot_response_logs', 'slack_channel_name')
    op.drop_column('slack_bot_response_logs', 'slack_user_name')
    op.drop_column('slack_bot_response_logs', 'response_type')
    sa.Enum(name='responsetype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_slack_connection_logs_workspace_id'), table_name='slack_connection_logs')
    op.drop_table('slack_connection_logs')
    sa.Enum(name='connectioneventtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
