"""add active_drive_file_ids to chat_conversations

Revision ID: e8530a5a5a0e
Revises: 9566994a20ee
Create Date: 2026-04-29 11:25:14.266629

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8530a5a5a0e"
down_revision: Union[str, Sequence[str], None] = "9566994a20ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_active_drive_files_conversation_id"), table_name="conversation_active_drive_files"
    )
    op.drop_index(
        op.f("ix_conversation_active_drive_files_drive_file_id"), table_name="conversation_active_drive_files"
    )
    op.drop_table("conversation_active_drive_files")
    op.add_column("chat_conversations", sa.Column("active_drive_file_ids", sa.Text(), nullable=True))
    op.drop_column("chat_messages", "attachments_json")
    op.drop_constraint(op.f("whitelisted_email_value_key"), "whitelisted_email", type_="unique")
    op.drop_index(op.f("ix_whitelisted_email_value"), table_name="whitelisted_email")
    op.create_index(op.f("ix_whitelisted_email_value"), "whitelisted_email", ["value"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whitelisted_email_value"), table_name="whitelisted_email")
    op.create_index(op.f("ix_whitelisted_email_value"), "whitelisted_email", ["value"], unique=False)
    op.create_unique_constraint(
        op.f("whitelisted_email_value_key"), "whitelisted_email", ["value"], postgresql_nulls_not_distinct=False
    )
    op.add_column("chat_messages", sa.Column("attachments_json", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("chat_conversations", "active_drive_file_ids")
    op.create_table(
        "conversation_active_drive_files",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("drive_file_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["chat_conversations.id"],
            name=op.f("conversation_active_drive_files_conversation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["drive_file_id"],
            ["drive_files.id"],
            name=op.f("conversation_active_drive_files_drive_file_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversation_active_drive_files_pkey")),
        sa.UniqueConstraint(
            "conversation_id",
            "drive_file_id",
            name=op.f("conversation_active_drive_fil_conversation_id_drive_file_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_conversation_active_drive_files_drive_file_id"),
        "conversation_active_drive_files",
        ["drive_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_active_drive_files_conversation_id"),
        "conversation_active_drive_files",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###
