"""add active_drive_file_id to conversations

Revision ID: e85d903dcb3b
Revises: i2b3c4d5e6f7
Create Date: 2026-04-17 18:15:48.600130

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e85d903dcb3b"
down_revision: Union[str, Sequence[str], None] = "i2b3c4d5e6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_conversations", sa.Column("active_drive_file_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("idx_conversation_uuid"), table_name="chat_conversations")
    op.create_index(
        op.f("ix_chat_conversations_active_drive_file_id"), "chat_conversations", ["active_drive_file_id"], unique=False
    )
    op.create_index(op.f("ix_chat_conversations_uuid"), "chat_conversations", ["uuid"], unique=True)
    op.create_foreign_key(
        None, "chat_conversations", "drive_files", ["active_drive_file_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "drive_files",
        "modified_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_files",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_files",
        "rag_error",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_folders",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_folders",
        "sync_error",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_oauth_tokens",
        "token_expiry",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("drive_oauth_tokens_user_id_key"), "drive_oauth_tokens", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("drive_oauth_tokens_user_id_key"), "drive_oauth_tokens", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "drive_oauth_tokens",
        "token_expiry",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "drive_folders",
        "sync_error",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_folders",
        "last_synced_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_files",
        "rag_error",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_files",
        "last_synced_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "drive_files",
        "modified_time",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(None, "chat_conversations", type_="foreignkey")
    op.drop_index(op.f("ix_chat_conversations_uuid"), table_name="chat_conversations")
    op.drop_index(op.f("ix_chat_conversations_active_drive_file_id"), table_name="chat_conversations")
    op.create_index(op.f("idx_conversation_uuid"), "chat_conversations", ["uuid"], unique=True)
    op.drop_column("chat_conversations", "active_drive_file_id")
    # ### end Alembic commands ###
