"""create llm_configs table

Revision ID: ed5bc53f5b16
Revises: acc6f4381f88
Create Date: 2026-04-17 15:07:16.059759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed5bc53f5b16'
down_revision: Union[str, Sequence[str], None] = 'acc6f4381f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_table('llm_configs',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('masked_key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_llm_config_name')
    )
    op.create_index('idx_llm_config_user', 'llm_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_llm_configs_is_deleted'), 'llm_configs', ['is_deleted'], unique=False)

    # Copy existing rows, generating names from provider + id
    op.execute("""
        INSERT INTO llm_configs
            (is_deleted, deleted_at, created_at, updated_at,
             id, user_id, name, provider, model,
             encrypted_key, masked_key, is_active, last_used_at)
        SELECT
            COALESCE(is_deleted, false),
            deleted_at,
            created_at,
            updated_at,
            id,
            user_id,
            provider || '-' || id::text AS name,
            provider,
            '' AS model,
            encrypted_key,
            masked_key,
            is_active,
            last_used_at
        FROM chat_provider_api_keys
    """)
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('llm_configs', 'id'),
            COALESCE((SELECT MAX(id) FROM llm_configs), 1),
            COALESCE((SELECT MAX(id) FROM llm_configs) IS NOT NULL, false)
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_llm_configs_is_deleted'), table_name='llm_configs')
    op.drop_index('idx_llm_config_user', table_name='llm_configs')
    op.drop_table('llm_configs')
    # ### end Alembic commands ###
