[workspace]
resolver = "3"

members = [
    "mcp",
    "backend/web-api",
    "backend/app_core",
]

[workspace.package]
repository = "https://github.com/edly-io/sparkth"
license = "MIT"

[profile.dist]
inherits = "release"
lto = "thin"

