"""remove user_id from rag_document_chunks

Revision ID: 19422defc371
Revises: d7f1c9deaf2c
Create Date: 2026-06-12 17:02:00.076524

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19422defc371"
down_revision: Union[str, Sequence[str], None] = "d7f1c9deaf2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_rag_chunks_user_source"), table_name="rag_document_chunks")
    op.drop_index(op.f("ix_rag_document_chunks_user_id"), table_name="rag_document_chunks")
    op.drop_constraint(op.f("rag_document_chunks_user_id_fkey"), "rag_document_chunks", type_="foreignkey")
    op.drop_column("rag_document_chunks", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_document_chunks", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("rag_document_chunks_user_id_fkey"), "rag_document_chunks", "user", ["user_id"], ["id"])
    op.create_index(op.f("ix_rag_document_chunks_user_id"), "rag_document_chunks", ["user_id"], unique=False)
    op.create_index("idx_rag_chunks_user_source", "rag_document_chunks", ["user_id", "source_name"], unique=False)
    # ### end Alembic commands ###
