"""add audit_events table

Revision ID: 3fafda1c666e
Revises: 9477cf5a43a0
Create Date: 2026-07-03 14:11:24.638316

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3fafda1c666e"
down_revision: Union[str, Sequence[str], None] = "9477cf5a43a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("actor_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("actor_label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("request_ip", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("target_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("target_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "old_values", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "new_values", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "tool_args", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("model_provider", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("canonical_bytes", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_events_category"), "audit_events", ["category"], unique=False)
    op.create_index(op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_category"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
