// Generated by scripts/dump_frontend_plugins.py. Do not edit.
// Backend plugins that declare a frontend page (FRONTEND_APPS hook).
// Regenerate with `make frontend.build.plugins`; tests fail on drift.

export const FRONTEND_PLUGIN_NAMES = ["chat", "google-drive", "slack"] as const;

export type FrontendPluginName = (typeof FRONTEND_PLUGIN_NAMES)[number];
