"""add user language

Revision ID: 0a2dfb2685ad
Revises: 5b68940ffec3
Create Date: 2026-08-07 18:28:51.061339

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a2dfb2685ad"
down_revision: Union[str, Sequence[str], None] = "5b68940ffec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "language")
    # ### end Alembic commands ###
