"""add org tables

Revision ID: 59aca6562143
Revises: 5c6ccf073bb7
Create Date: 2026-07-27 10:59:45.856822

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59aca6562143"
down_revision: Union[str, Sequence[str], None] = "5c6ccf073bb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_unit",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["org_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_unit_name"), "org_unit", ["name"], unique=False)
    op.create_index(op.f("ix_org_unit_parent_id"), "org_unit", ["parent_id"], unique=False)
    op.create_index(op.f("ix_org_unit_path"), "org_unit", ["path"], unique=False)
    op.create_index(
        "uq_org_unit_sibling_name", "org_unit", ["name", sa.literal_column("coalesce(parent_id, 0)")], unique=True
    )
    op.create_table(
        "org_membership",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_unit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_membership_is_deleted"), "org_membership", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_org_membership_org_unit_id"), "org_membership", ["org_unit_id"], unique=False)
    op.create_index(op.f("ix_org_membership_user_id"), "org_membership", ["user_id"], unique=False)
    op.create_index(
        "uq_org_membership_active",
        "org_membership",
        ["user_id", "org_unit_id"],
        unique=True,
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_org_membership_active",
        table_name="org_membership",
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_org_membership_user_id"), table_name="org_membership")
    op.drop_index(op.f("ix_org_membership_org_unit_id"), table_name="org_membership")
    op.drop_index(op.f("ix_org_membership_is_deleted"), table_name="org_membership")
    op.drop_table("org_membership")
    op.drop_index("uq_org_unit_sibling_name", table_name="org_unit")
    op.drop_index(op.f("ix_org_unit_path"), table_name="org_unit")
    op.drop_index(op.f("ix_org_unit_parent_id"), table_name="org_unit")
    op.drop_index(op.f("ix_org_unit_name"), table_name="org_unit")
    op.drop_table("org_unit")
    # ### end Alembic commands ###
