"""drop conversation system_prompt

Revision ID: 5b68940ffec3
Revises: 5c6ccf073bb7
Create Date: 2026-08-07 17:59:35.093474

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b68940ffec3"
down_revision: Union[str, Sequence[str], None] = "5c6ccf073bb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_conversations", "system_prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_conversations", sa.Column("system_prompt", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
