"""add organization tables

Revision ID: 94c26cf76059
Revises: 5c6ccf073bb7
Create Date: 2026-07-27 15:18:16.984869

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94c26cf76059"
down_revision: Union[str, Sequence[str], None] = "5c6ccf073bb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizational_unit",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizational_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizational_unit_name"), "organizational_unit", ["name"], unique=False)
    op.create_index(op.f("ix_organizational_unit_parent_id"), "organizational_unit", ["parent_id"], unique=False)
    op.create_index(op.f("ix_organizational_unit_path"), "organizational_unit", ["path"], unique=False)
    op.create_index(
        "uq_organizational_unit_sibling_name",
        "organizational_unit",
        ["name", sa.literal_column("coalesce(parent_id, 0)")],
        unique=True,
    )
    op.create_table(
        "organization_membership",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organizational_unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organizational_unit_id"],
            ["organizational_unit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_membership_is_deleted"), "organization_membership", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_organization_membership_organizational_unit_id"),
        "organization_membership",
        ["organizational_unit_id"],
        unique=False,
    )
    op.create_index(op.f("ix_organization_membership_user_id"), "organization_membership", ["user_id"], unique=False)
    op.create_index(
        "uq_organization_membership_active",
        "organization_membership",
        ["user_id", "organizational_unit_id"],
        unique=True,
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_organization_membership_active",
        table_name="organization_membership",
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_organization_membership_user_id"), table_name="organization_membership")
    op.drop_index(op.f("ix_organization_membership_organizational_unit_id"), table_name="organization_membership")
    op.drop_index(op.f("ix_organization_membership_is_deleted"), table_name="organization_membership")
    op.drop_table("organization_membership")
    op.drop_index("uq_organizational_unit_sibling_name", table_name="organizational_unit")
    op.drop_index(op.f("ix_organizational_unit_path"), table_name="organizational_unit")
    op.drop_index(op.f("ix_organizational_unit_parent_id"), table_name="organizational_unit")
    op.drop_index(op.f("ix_organizational_unit_name"), table_name="organizational_unit")
    op.drop_table("organizational_unit")
    # ### end Alembic commands ###
