"""add responsibility to chat conversations

Revision ID: 9e93bac1bf0b
Revises: 80d482b38d01
Create Date: 2026-10-02 12:43:45.138665

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e93bac1bf0b"
down_revision: Union[str, Sequence[str], None] = "80d482b38d01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_conversations", sa.Column("responsibility", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_conversations", "responsibility")
    # ### end Alembic commands ###
