"""add group tables

Revision ID: e69b161ed8ee
Revises: 4aac177b2327
Create Date: 2026-07-27 10:11:15.208659

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e69b161ed8ee"
down_revision: Union[str, Sequence[str], None] = "b5bf23a5f00e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_group",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_group_name"), "user_group", ["name"], unique=True)
    op.create_table(
        "group_membership",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_membership_group_id"), "group_membership", ["group_id"], unique=False)
    op.create_index(op.f("ix_group_membership_is_deleted"), "group_membership", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_group_membership_user_id"), "group_membership", ["user_id"], unique=False)
    op.create_index(
        "uq_group_membership_active",
        "group_membership",
        ["user_id", "group_id"],
        unique=True,
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "group_role_assignment",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("scope_object_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_role_assignment_group_id"), "group_role_assignment", ["group_id"], unique=False)
    op.create_index(op.f("ix_group_role_assignment_is_deleted"), "group_role_assignment", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_group_role_assignment_role_id"), "group_role_assignment", ["role_id"], unique=False)
    op.create_index(op.f("ix_group_role_assignment_scope"), "group_role_assignment", ["scope"], unique=False)
    op.create_index(
        op.f("ix_group_role_assignment_scope_object_id"), "group_role_assignment", ["scope_object_id"], unique=False
    )
    op.create_index(
        "uq_group_role_assignment_active",
        "group_role_assignment",
        ["group_id", "role_id", "scope", sa.literal_column("coalesce(scope_object_id, '')")],
        unique=True,
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_group_role_assignment_active",
        table_name="group_role_assignment",
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_group_role_assignment_scope_object_id"), table_name="group_role_assignment")
    op.drop_index(op.f("ix_group_role_assignment_scope"), table_name="group_role_assignment")
    op.drop_index(op.f("ix_group_role_assignment_role_id"), table_name="group_role_assignment")
    op.drop_index(op.f("ix_group_role_assignment_is_deleted"), table_name="group_role_assignment")
    op.drop_index(op.f("ix_group_role_assignment_group_id"), table_name="group_role_assignment")
    op.drop_table("group_role_assignment")
    op.drop_index(
        "uq_group_membership_active",
        table_name="group_membership",
        sqlite_where=sa.text("is_deleted = 0"),
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_group_membership_user_id"), table_name="group_membership")
    op.drop_index(op.f("ix_group_membership_is_deleted"), table_name="group_membership")
    op.drop_index(op.f("ix_group_membership_group_id"), table_name="group_membership")
    op.drop_table("group_membership")
    op.drop_index(op.f("ix_user_group_name"), table_name="user_group")
    op.drop_table("user_group")
    # ### end Alembic commands ###
