"""Dump the backend-declared frontend plugin list as TypeScript, offline.

Instantiating the plugin loader registers every plugin's hooks with no DB,
server, or event loop. The output is the generated frontend module listing the
plugins that declare a frontend page (the ``FRONTEND_APPS`` hook), sorted so
the file is diff-stable.

With no arguments the module is written to stdout, which is how it is inspected
by hand. Pass ``-o/--output <path>`` to write a file instead; the write is
atomic (temp file in the target's directory, then replaced), so a failed dump
leaves the previous file intact rather than truncating it the way ``> file``
redirection does.

The generated module is committed as ``frontend/lib/plugins/generated.ts``
(regenerate with ``make frontend.build.plugins``); tests on both tiers fail
when the committed file drifts from the declarations.
"""

import argparse
import logging
import os
import sys
import tempfile
from pathlib import Path

# Redirect all log output to stderr before importing app modules so that the
# only thing written to stdout is the generated TypeScript (see
# scripts/dump_openapi.py for the rationale).
logging.basicConfig(stream=sys.stderr)

from sparkth.lib.frontend import plugin_has_frontend  # noqa: E402
from sparkth.lib.plugins import get_plugin_loader  # noqa: E402

HEADER = """\
// Generated by scripts/dump_frontend_plugins.py. Do not edit.
// Backend plugins that declare a frontend page (FRONTEND_APPS hook).
// Regenerate with `make frontend.build.plugins`; tests fail on drift.
"""


def render() -> str:
    """Render the generated TypeScript module for the declared frontend plugins."""
    loader = get_plugin_loader()
    names = sorted(name for name, _ in loader.get_loaded_plugins() if plugin_has_frontend(name))
    quoted = ", ".join(f'"{name}"' for name in names)
    return (
        f"{HEADER}\n"
        f"export const FRONTEND_PLUGIN_NAMES = [{quoted}] as const;\n"
        "\n"
        "export type FrontendPluginName = (typeof FRONTEND_PLUGIN_NAMES)[number];\n"
    )


def _write_atomically(path: Path, contents: str) -> None:
    """Replace ``path`` with ``contents`` only once the full dump is in hand."""
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as tmp:
        tmp.write(contents)
        tmp_path = Path(tmp.name)
    os.replace(tmp_path, path)


def main(argv: list[str] | None = None) -> None:
    """Write the generated module to ``--output``, or to stdout when it is omitted."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="file to write the generated module to (default: stdout)",
    )
    args = parser.parse_args(argv)

    contents = render()
    if args.output is None:
        sys.stdout.write(contents)
    else:
        _write_atomically(args.output, contents)


if __name__ == "__main__":
    main()
