"""Dump the backend-declared frontend plugin list to stdout as TypeScript, offline.

Instantiating the plugin loader registers every plugin's hooks with no DB,
server, or event loop. The output is the generated frontend module listing the
plugins that declare a frontend page (the ``FRONTEND_APPS`` hook), sorted so
the file is diff-stable. It is committed as
``frontend/lib/plugins/generated.ts`` (regenerate with
``make frontend.build.plugins``); tests on both tiers fail when the committed
file drifts from the declarations.
"""

import logging
import sys

# Redirect all log output to stderr before importing app modules so that the
# only thing written to stdout is the generated TypeScript (see
# scripts/dump_openapi.py for the rationale).
logging.basicConfig(stream=sys.stderr)

from sparkth.lib.frontend import plugin_has_frontend  # noqa: E402
from sparkth.lib.plugins import get_plugin_loader  # noqa: E402

HEADER = """\
// Generated by scripts/dump_frontend_plugins.py. Do not edit.
// Backend plugins that declare a frontend page (FRONTEND_APPS hook).
// Regenerate with `make frontend.build.plugins`; tests fail on drift.
"""


def main() -> None:
    loader = get_plugin_loader()
    names = sorted(name for name, _ in loader.get_loaded_plugins() if plugin_has_frontend(name))
    quoted = ", ".join(f'"{name}"' for name in names)
    sys.stdout.write(HEADER)
    sys.stdout.write("\n")
    sys.stdout.write(f"export const FRONTEND_PLUGIN_NAMES = [{quoted}] as const;\n")
    sys.stdout.write("\n")
    sys.stdout.write("export type FrontendPluginName = (typeof FRONTEND_PLUGIN_NAMES)[number];\n")


if __name__ == "__main__":
    main()
