"""Structural interfaces app/llm depends on, free of app.core couplings."""

from typing import Protocol


class SupportsEncryption(Protocol):
    """Encrypt/decrypt interface required by LLMConfigService."""

    def encrypt(self, plaintext: str) -> str: ...
    def decrypt(self, encrypted_text: str) -> str: ...


class SupportsCache(Protocol):
    """Async cache interface required by LLMConfigService."""

    def make_key(self, *parts: str) -> str: ...
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int | None = None) -> bool: ...
    async def delete(self, key: str) -> bool: ...
